spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mag?characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 6000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      filters: stat,wall,log4j
  thymeleaf:
    cache: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

mybatis:
  mapper-locations: classpath:spring/sqlmap/*.xml
  type-aliases-package: com.example.pay.model
server:
  port: 8081
  servlet:
    context-path: /pay
